version: '3.7'

services:
    rss_web:
        build: .
        command: gunicorn config.wsgi --config config/gunicorn_conf.py --bind 0.0.0.0:$PORT --log-level debug
        container_name: rss_web
        image: rss_web
        volumes:
            - .:/code
            - static-content:/static
        ports:
            - "8080:8080"
        depends_on:
            - rss_postgres
            - rss_rabbitmq
        links:
            - rss_postgres
        environment:
            DATABASE_URL: "postgres://root:postgres@rss_postgres:5432/rss_db"
            PORT: 8080

    rss_postgres:
        container_name: rss_postgres
        image: postgres:11
        environment:
            POSTGRES_DB: rss_db
            POSTGRES_USER: root
            POSTGRES_PASSWORD: postgres
        volumes:
            - /var/lib/postgresql/data/
        ports:
            - "5432:5432"
        restart: always

    rss_rabbitmq:
        container_name: rss_rabbitmq
        image: "rabbitmq:3.8.0-management-alpine"
        hostname: "rss_rabbitmq"
        environment:
            RABBITMQ_DEFAULT_USER: "rabbitmq"
            RABBITMQ_DEFAULT_PASS: "rabbitmq"
            RABBITMQ_DEFAULT_VHOST: "celery_vhost"
        ports:
            - "15672:15672"
            - "5672:5672"

    celery:
        build: .
        command: celery -A config worker -l info
        volumes:
            - .:/code
        depends_on:
            - rss_postgres
            - rss_rabbitmq

    celery-beat:
        build: .
        command: celery -A config beat -l info
        volumes:
            - .:/code
        depends_on:
            - rss_postgres
            - rss_rabbitmq

networks:
    default:
        external:
            name: local

volumes:
    postgres_data:
    static-content: