# Generated by Django 3.1.2 on 2020-11-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feeds', '0002_auto_20201104_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedfollow',
            options={'verbose_name': 'Feed Follow', 'verbose_name_plural': 'Feed Follow'},
        ),
    ]
