# Generated by Django 3.1.2 on 2020-11-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feeds', '0003_auto_20201104_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='link',
            field=models.URLField(),
        ),
    ]
