# Generated by Django 3.1.2 on 2020-11-04 23:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rss_feeds', '0004_auto_20201104_2024'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedfollow',
            unique_together={('user', 'feed')},
        ),
    ]
