# Generated by Django 3.1.2 on 2020-11-06 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rss_feeds', '0006_auto_20201104_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feed_follows', to='auth.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FeedFollow',
        ),
    ]
