# Generated by Django 3.1.2 on 2020-11-06 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rss_feeds', '0007_auto_20201106_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ('modified_on',)},
        ),
        migrations.AlterModelOptions(
            name='feeditem',
            options={'ordering': ('modified_on',), 'verbose_name': 'Feed Item', 'verbose_name_plural': 'Feed Items'},
        ),
        migrations.RemoveField(
            model_name='feed',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='feeditem',
            name='is_permalink',
        ),
        migrations.RemoveField(
            model_name='feeditem',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='feed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to=settings.AUTH_USER_MODEL),
        ),
    ]
