# Generated by Django 3.1.2 on 2020-11-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feeds', '0008_auto_20201106_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='description',
            field=models.TextField(),
        ),
    ]
