# Generated by Django 3.1.2 on 2020-11-07 19:22

from django.db import migrations, models
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('rss_feeds', '0009_auto_20201106_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='last_updated',
            field=models.DateTimeField(default=datetime.now()),
            preserve_default=False,
        ),
    ]
