# Generated by Django 3.1.2 on 2020-11-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feeds', '0010_feed_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='last_updated',
            field=models.CharField(max_length=50),
        ),
    ]
