# Generated by Django 3.1.2 on 2020-11-08 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feeds', '0012_auto_20201108_1127'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feeditem',
            unique_together={('feed', 'item_id')},
        ),
    ]
