# Generated by Django 3.1.2 on 2020-11-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feeds', '0013_auto_20201108_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='feeditem',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='feed',
            name='rss_server_last_updated',
            field=models.CharField(default='', help_text='Last updated date/time from RSS server', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeditem',
            name='rss_server_last_updated',
            field=models.CharField(default='', help_text='Last updated date/time from RSS server', max_length=100),
            preserve_default=False,
        ),
    ]
