# Generated by Django 3.1.2 on 2020-11-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feeds', '0014_auto_20201108_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='update_success',
            field=models.BooleanField(default=True),
        ),
    ]
