# Generated by Django 3.1.2 on 2020-11-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feeds', '0015_feed_update_success'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ('-modified_on',)},
        ),
        migrations.AlterModelOptions(
            name='feeditem',
            options={'ordering': ('-modified_on',), 'verbose_name': 'Feed Item', 'verbose_name_plural': 'Feed Items'},
        ),
    ]
